sagerx:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: postgres
      port: 5432
      user: sagerx
      pass: sagerx
      dbname: sagerx
      schema: sagerx_dev

    prod:
      type: postgres
      threads: 1
      host: postgres
      port: 5432
      user: sagerx
      pass: sagerx
      dbname: sagerx
      schema: sagerx

  target: dev
